name: HCS-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pip:
      - apscheduler==3.11.0
      - asgiref==3.8.1
      - black==25.1.0
      - click==8.1.8
      - contourpy==1.3.2
      - crispy-bootstrap5==2024.10
      - cycler==0.12.1
      - diff-match-patch==20241021
      - django==5.0.4
      - django-allauth==0.63.3
      - django-crispy-forms>=2.3
      - django-import-export
      - django-crontab
      - django-mathfilters
      - django-simple-history
      - environs
      - fonttools==4.53.0
      - gunicorn==22.0.0
      - h11==0.14.0
      - httptools==0.6.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - plotly==5.22.0
      - pymdown-extensions==10.8
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - rich==13.7.1
      - scipy==1.13.1
      - six==1.16.0
      - sniffio==1.3.1
      - sqlparse==0.5.0
      - starlette==0.37.2
      - tomli==2.0.1
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.30.1
      - watchfiles==0.21.0
      - websockets==12.0
