# Generated by Django 5.1.5 on 2025-03-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance_km",
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.CharField(max_length=255),
        ),
    ]
