# Generated by Django 5.1.5 on 2025-03-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0002_route_distance_km_alter_route_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripproduct",
            name="unit",
            field=models.CharField(
                choices=[("Pallets", "Pallets"), ("Cases", "Cases")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="truckcompany",
            name="email",
            field=models.CharField(max_length=30),
        ),
    ]
