# Generated by Django 5.1.5 on 2025-03-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0004_trip_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="user_name",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
