# Generated by Django 5.1.5 on 2025-03-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0005_trip_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="user",
            new_name="clerk",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="user_name",
        ),
    ]
