# Generated by Django 5.1.5 on 2025-03-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0009_alter_triproute_actual_time_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="triplog.route",
            ),
        ),
        migrations.AddField(
            model_name="triproute",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_routes",
                to="triplog.driver",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="triproute",
            name="actual_time_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
