# Generated by Django 5.1.5 on 2025-03-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0011_remove_trip_route_remove_triproute_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="triplog.route",
            ),
            preserve_default=False,
        ),
    ]
