# Generated by Django 5.1.5 on 2025-03-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0012_trip_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="triplog.route",
            ),
        ),
    ]
