# Generated by Django 5.1.5 on 2025-03-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0014_remove_trip_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="triplog.triproute",
            ),
            preserve_default=False,
        ),
    ]
