# Generated by Django 5.1.5 on 2025-03-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0015_trip_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="route",
        ),
    ]
