# Generated by Django 5.1.5 on 2025-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triplog", "0016_remove_trip_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("total_points", models.IntegerField(default=0)),
                ("rank_1_count", models.IntegerField(default=0)),
                ("rank_2_count", models.IntegerField(default=0)),
                ("rank_3_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-total_points", "-rank_1_count", "-rank_2_count"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyDriverRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("month", models.DateField()),
                ("rank", models.IntegerField()),
                ("trips_completed", models.IntegerField()),
                ("points_earned", models.IntegerField()),
            ],
            options={
                "ordering": ["-month", "rank"],
                "unique_together": {("driver_name", "month")},
            },
        ),
    ]
